site_name: Notes on Math, Physics & More
site_url: https://boonware.github.io/notes/

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  navigation_depth: 3

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: "#"
      toc_depth: 3

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Mathematics:
    - Axiomatic Set Theory:
      - Logic: axiomatic_set_theory/logic.md
      - Axiomatic Systems & Proofs: axiomatic_set_theory/axiomatic_systems_and_proofs.md
      - Zermelo-Fraenkel Axioms: axiomatic_set_theory/zermelo_fraenkel_axioms.md

    - Vector Spaces:
      - Dual Space: vector_spaces/dual_space.md
      - Hilbert Space: vector_spaces/hilbert_space.md

    - Linear Operators:
      - Representation: linear_operators/representation.md
      - Basis Dependence: linear_operators/basis_dependence.md

    - Complex Analysis:
      - Complex Numbers: complex_analysis/complex_numbers.md
      - Contour Integration: complex_analysis/contour_integration.md

    - Group Theory:
      - Group Actions: group_theory/group_actions.md
      - Exercise Solutions (Stone & Goldbart): group_theory/stone_goldbart_solutions.md

    - Statistics:
      - Introduction: statistics/introduction.md
      - Discrete Probability Distributions: statistics/discrete_probability_distributions.md
      - Continuous Probability Distributions: statistics/continuous_probability_distributions.md
      - Hypothesis Testing: statistics/hypothesis_testing.md
      - Z-Score & Z-Test: statistics/z_test.md
      - Student's T-Test: statistics/t_test.md
      - Pearson's Chi-Squared Test: statistics/chi_squared_test.md
      - Maximum Likelihood Estimation: statistics/maximum_likelihood_estimation.md
      - Power Transforms: statistics/power_transforms.md
      - Correlation: statistics/correlation.md
    
    - Numerical Analysis:
      - Floating-Point: numerical_analysis/floating_point.md

    - "Green's Functions":
      - Introduction: greens_functions/intro.md
      
  - Physics:
    - Special Relativity:
      - Galilean Relativity: special_relativity/galilean_relativity.md
      - Spacetime: special_relativity/spacetime.md
    - Quantum Mechanics:
      - Introduction: quantum_mechanics/introduction.md
      - Schrodinger Equation: quantum_mechanics/schrodinger_equation.md
  - Quantum Computing:
    - Teleportation: quantum_computation/teleportation.md
    - Quantum Parallelism & Deutsch's Algorithm: quantum_computation/deutschs_algorithm.md
    - Deutsch's Algorithm: quantum_computation/deutschs_algorithm.md
    - Deutsch-Josza Algorithm: quantum_computation/deutsch_josza_algorithm.md
  
  - Machine Learning:
    - Introduction: machine_learning/introduction.md
    - Linear Regression: machine_learning/linear_regression.md
    - Feature Scaling: machine_learning/feature_scaling.md
    - Logistic Regression: machine_learning/logistic_regression.md
    - Natural Language Processing:
        - TF-IDF: nlp/intro.md
  